micronaut:
  application:
    name: example-jpa
jackson:
  bean-introspection-module: true
---
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa:
  default:
    properties:
      org:
        hibernate:
          flushMode: COMMIT
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: create-drop
        show_sql: true
        use_sql_comments: true

